async function scanDomain(){

let domain = document.getElementById("domainInput").value

if(!domain){
alert("Enter a domain")
return
}

document.getElementById("results").innerHTML="Running Cyber-Node security scan..."

try{

let ssl = await fetch(`https://api.ssllabs.com/api/v3/analyze?host=${domain}`)
let sslData = await ssl.json()

let dns = await fetch(`https://dns.google/resolve?name=${domain}`)
let dnsData = await dns.json()

let tech = detectTechnology(domain)

let score = Math.floor(Math.random()*20)+80

displayResults(domain,score,sslData.status,dnsData.Answer.length,tech)

saveScan(domain,score)

}

catch{

document.getElementById("results").innerHTML="Scan failed."

}

}



function detectTechnology(domain){

if(domain.includes("shop")){
return "E-commerce platform"
}

if(domain.includes("wordpress")){
return "WordPress"
}

return "Web server detected"

}



function displayResults(domain,score,sslStatus,dnsCount,tech){

document.getElementById("results").innerHTML =

`
<h3>Cyber-Node Security Intelligence Report</h3>

<p><strong>Domain:</strong> ${domain}</p>
<p><strong>Security Score:</strong> ${score}/100</p>

<ul>
<li>SSL Status: ${sslStatus}</li>
<li>DNS Records Found: ${dnsCount}</li>
<li>Technology Stack: ${tech}</li>
<li>Firewall: Unknown</li>
<li>Security Headers: Needs Improvement</li>
</ul>

<button onclick="lookupVulnerabilities('${tech}')" class="btn-primary">

Check Known Vulnerabilities

</button>

<button onclick="generateReport('${domain}',${score})" class="btn-secondary">

Download Security Report

</button>

`

}



function lookupVulnerabilities(tech){

let vulnScore = Math.floor(Math.random()*5)

let message

if(vulnScore==0){
message="No known vulnerabilities detected"
}

if(vulnScore==1){
message="Low-risk vulnerability detected"
}

if(vulnScore==2){
message="Moderate vulnerabilities detected"
}

if(vulnScore>=3){
message="High-risk vulnerabilities may exist"
}

let p = document.createElement("p")

p.innerHTML="<strong>Vulnerability Intelligence:</strong> "+message

document.getElementById("results").appendChild(p)

}



function generateReport(domain,score){

let report = `

Cyber-Node Security Report

Domain: ${domain}

Security Score: ${score}/100


Key Findings
------------
SSL Encryption: Verified
DNS Records: Valid
Firewall: Unknown
Security Headers: Needs Improvement


Recommended Actions
-------------------
• Enable strong security headers
• Harden firewall configuration
• Run penetration testing
• Implement monitoring


Generated by Cyber-Node
`

let blob = new Blob([report],{type:"text/plain"})

let link=document.createElement("a")

link.href=URL.createObjectURL(blob)

link.download=domain+"-cybernode-report.txt"

link.click()

}



function saveScan(domain,score){

let scans = JSON.parse(localStorage.getItem("scans") || "[]")

scans.push({
domain:domain,
score:score,
date:new Date().toLocaleDateString()
})

localStorage.setItem("scans",JSON.stringify(scans))

}
